import React, { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { doc, getDoc, collection, query, where, getDocs, limit } from 'firebase/firestore';
import { db } from '../../lib/firebase';

/**
 * Programmatic SEO Landing Page
 * Route: /:lang/rechnung-erstellen/:slug  (DE/AT)
 *        /:lang/criar-fatura/:slug        (PT)
 *        /:lang/crear-factura/:slug       (ES)
 *        /:lang/creer-facture/:slug       (FR)
 *        /en/invoice-template/:slug       (EN)
 *
 * Content is generated by the SEO Agent and stored in seo_content_queue Firestore.
 */

const LANG_CONFIG = {
    de: { cta: 'Kostenlos starten', ctaUrl: '/login', trustText: 'Bereits von tausenden Unternehmen in Deutschland genutzt.' },
    pt: { cta: 'Começar Grátis', ctaUrl: '/login', trustText: 'Usado por milhares de empresas em Portugal.' },
    es: { cta: 'Empezar Gratis', ctaUrl: '/login', trustText: 'Usado por miles de empresas en España.' },
    fr: { cta: 'Commencer Gratuitement', ctaUrl: '/login', trustText: 'Utilisé par des milliers d\'entreprises en France.' },
    en: { cta: 'Start for Free', ctaUrl: '/login', trustText: 'Trusted by thousands of businesses worldwide.' },
};

const COUNTRY_SLUG_MAP = {
    de: { path: 'rechnung-erstellen', country: 'DE' },
    pt: { path: 'criar-fatura', country: 'PT' },
    es: { path: 'crear-factura', country: 'ES' },
    fr: { path: 'creer-facture', country: 'FR' },
    en: { path: 'invoice-template', country: 'EN' },
};

const SeoLandingPage = () => {
    const { lang, slug } = useParams();
    const navigate = useNavigate();
    const [page, setPage] = useState(null);
    const [loading, setLoading] = useState(true);
    const [relatedPages, setRelatedPages] = useState([]);

    const langCfg = LANG_CONFIG[lang] || LANG_CONFIG.en;
    const countryInfo = COUNTRY_SLUG_MAP[lang];

    useEffect(() => {
        const load = async () => {
            if (!countryInfo) { navigate('/'); return; }

            try {
                const docId = `prog_${countryInfo.country.toLowerCase()}_${slug}`;
                const snap = await getDoc(doc(db, 'seo_content_queue', docId));

                if (!snap.exists() || snap.data().status === 'draft') {
                    navigate('/');
                    return;
                }

                setPage(snap.data());

                // Meta tags
                const data = snap.data();
                document.title = `${data.title} | BayFatura`;
                let metaDesc = document.querySelector('meta[name="description"]');
                if (!metaDesc) { metaDesc = document.createElement('meta'); metaDesc.name = 'description'; document.head.appendChild(metaDesc); }
                metaDesc.content = data.metaDescription || data.title;

                // Related pages
                const relSnap = await getDocs(
                    query(collection(db, 'seo_content_queue'),
                        where('country', '==', countryInfo.country),
                        where('type', '==', 'programmatic_page'),
                        where('status', 'in', ['ready_to_publish', 'published']),
                        limit(4)
                    )
                );
                setRelatedPages(relSnap.docs
                    .map(d => ({ id: d.id, ...d.data() }))
                    .filter(p => p.slug !== slug)
                    .slice(0, 3)
                );
            } catch (err) {
                console.error('SEO page load error:', err);
                navigate('/');
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [lang, slug]);

    if (loading) {
        return (
            <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#f8fafc' }}>
                <div style={{ textAlign: 'center' }}>
                    <div style={{ width: 40, height: 40, border: '3px solid #e2e8f0', borderTop: '3px solid #2563eb', borderRadius: '50%', margin: '0 auto 16px', animation: 'spin 1s linear infinite' }} />
                </div>
            </div>
        );
    }

    if (!page) return null;

    const content = page.content || {};
    const features = Array.isArray(content.features) ? content.features : [];
    const faq = Array.isArray(content.faq) ? content.faq : [];

    return (
        <div style={{ fontFamily: 'Inter, sans-serif', background: '#fff', color: '#1e293b' }}>
            {/* Nav */}
            <nav style={{ padding: '16px 24px', borderBottom: '1px solid #e2e8f0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, background: '#fff', zIndex: 100 }}>
                <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
                    <img src="/logo.png" alt="BayFatura" style={{ height: 32 }} />
                    <span style={{ fontWeight: 700, fontSize: '1.1rem', color: '#1e293b' }}>BayFatura</span>
                </Link>
                <Link to={langCfg.ctaUrl} style={{ background: '#2563eb', color: '#fff', padding: '10px 20px', borderRadius: 10, textDecoration: 'none', fontWeight: 600, fontSize: '0.9rem' }}>
                    {langCfg.cta}
                </Link>
            </nav>

            {/* Hero */}
            <section style={{ maxWidth: 800, margin: '0 auto', padding: '64px 24px 48px', textAlign: 'center' }}>
                <h1 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.8rem)', fontWeight: 800, lineHeight: 1.15, marginBottom: 20, color: '#0f172a' }}>
                    {content.h1 || page.title}
                </h1>
                <p style={{ fontSize: '1.1rem', color: '#475569', lineHeight: 1.7, marginBottom: 32, maxWidth: 600, margin: '0 auto 32px' }}>
                    {content.hero || page.metaDescription}
                </p>
                <Link to={langCfg.ctaUrl} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: '#2563eb', color: '#fff', padding: '14px 32px', borderRadius: 12, textDecoration: 'none', fontWeight: 700, fontSize: '1rem', boxShadow: '0 4px 14px rgba(37,99,235,0.3)' }}>
                    {langCfg.cta} →
                </Link>
                <p style={{ marginTop: 16, fontSize: '0.85rem', color: '#94a3b8' }}>{langCfg.trustText}</p>
            </section>

            {/* Features */}
            {features.length > 0 && (
                <section style={{ maxWidth: 900, margin: '0 auto', padding: '48px 24px' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 24 }}>
                        {features.map((feat, i) => (
                            <div key={i} style={{ padding: 24, background: '#f8fafc', borderRadius: 16, border: '1px solid #e2e8f0' }}>
                                <div style={{ width: 40, height: 40, background: '#eff6ff', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16, fontSize: '1.2rem' }}>
                                    {['✅', '⚡', '🌍', '🔒', '📊', '💼'][i] || '✅'}
                                </div>
                                <p style={{ margin: 0, color: '#334155', lineHeight: 1.6, fontSize: '0.95rem' }}>{feat}</p>
                            </div>
                        ))}
                    </div>
                </section>
            )}

            {/* CTA Banner */}
            <section style={{ background: 'linear-gradient(135deg, #1e40af, #2563eb)', padding: '48px 24px', textAlign: 'center' }}>
                <h2 style={{ color: '#fff', fontSize: '1.8rem', fontWeight: 800, marginBottom: 16 }}>
                    {content.cta || langCfg.cta}
                </h2>
                <Link to={langCfg.ctaUrl} style={{ display: 'inline-flex', background: '#fff', color: '#2563eb', padding: '14px 32px', borderRadius: 12, textDecoration: 'none', fontWeight: 700, fontSize: '1rem' }}>
                    {langCfg.cta}
                </Link>
            </section>

            {/* FAQ */}
            {faq.length > 0 && (
                <section style={{ maxWidth: 700, margin: '0 auto', padding: '64px 24px' }}>
                    <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: 32, textAlign: 'center' }}>FAQ</h2>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                        {faq.map((item, i) => (
                            <details key={i} style={{ background: '#f8fafc', borderRadius: 12, padding: '16px 20px', border: '1px solid #e2e8f0' }}>
                                <summary style={{ fontWeight: 600, cursor: 'pointer', color: '#1e293b', fontSize: '0.95rem' }}>
                                    {item.q}
                                </summary>
                                <p style={{ margin: '12px 0 0', color: '#475569', lineHeight: 1.7, fontSize: '0.9rem' }}>{item.a}</p>
                            </details>
                        ))}
                    </div>
                </section>
            )}

            {/* Related Pages */}
            {relatedPages.length > 0 && (
                <section style={{ maxWidth: 900, margin: '0 auto', padding: '0 24px 64px' }}>
                    <h2 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: 20, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em', fontSize: '0.8rem' }}>
                        Weitere Themen / Related
                    </h2>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12 }}>
                        {relatedPages.map(p => (
                            <Link key={p.id} to={`/${lang}/${COUNTRY_SLUG_MAP[lang]?.path}/${p.slug}`}
                                style={{ padding: '8px 16px', background: '#f1f5f9', borderRadius: 8, textDecoration: 'none', color: '#475569', fontSize: '0.85rem', fontWeight: 500 }}>
                                {p.title}
                            </Link>
                        ))}
                    </div>
                </section>
            )}

            {/* Footer */}
            <footer style={{ borderTop: '1px solid #e2e8f0', padding: '24px', textAlign: 'center', color: '#94a3b8', fontSize: '0.85rem' }}>
                <Link to="/" style={{ color: '#2563eb', textDecoration: 'none', fontWeight: 600 }}>BayFatura</Link>
                {' · '}
                <Link to="/privacy" style={{ color: '#94a3b8', textDecoration: 'none' }}>Datenschutz</Link>
                {' · '}
                <Link to="/impressum" style={{ color: '#94a3b8', textDecoration: 'none' }}>Impressum</Link>
            </footer>
        </div>
    );
};

export default SeoLandingPage;
