import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    de: {
        // Sidebar
        dashboard: 'Übersicht',
        appName: 'BayFatura',
        newInvoice: 'Neue Rechnung',
        quotes: 'Angebote',
        archive: 'Archiv',
        reports: 'Berichte',
        expenses: 'Ausgaben',
        recurring: 'Wiederkehrend',
        users: 'Benutzerverwaltung',
        messages: 'Nachrichten',
        settings: 'Einstellungen',

        // Common / Actions
        save: 'Speichern',
        cancel: 'Abbrechen',
        delete: 'Löschen',
        edit: 'Bearbeiten',
        print: 'Drucken',
        loading: 'Lädt...',
        total: 'Gesamtbetrag',
        status: 'Status',
        date: 'Datum',
        customer: 'Kunde',
        invoiceNumber: 'Rechnungs-Nr.',
        quoteNumber: 'Angebots-Nr.',
        saveAndPrint: 'Speichern & Drucken',
        actions: 'Aktionen',
        back: 'Zurück',
        convertToInvoice: 'In Rechnung umwandeln',
        validUntil: 'Gültig bis',
        newQuote: 'Neues Angebot',
        quote: 'Angebot',
        quotesDesc: 'Angebote verwalten und in Rechnungen umwandeln.',
        proforma: 'Proforma',
        debts: 'Offene Posten',
        stock: 'Lager / Bestand',
        dailyReports: 'Tagesberichte',
        progress: 'Fortschritt',
        role: 'Rolle',
        site: 'Baustelle',
        searchUsers: 'Benutzer suchen...',
        addEmployee: 'Mitarbeiter hinzufügen',
        notification: 'Benachrichtigung',

        // Dashboard
        welcome: 'Willkommen',
        revenue: 'Gesamtumsatz',
        netProfit: 'Gewinn (Netto)',
        recentInvoices: 'Aktuelle Rechnungen',
        overviewText: 'Hier ist die Übersicht deiner Rechnungen und Finanzen.',

        // Settings
        companySettings: 'Firmeneinstellungen',
        language: 'Sprache',
        appLanguageLabel: 'Anwendungs-Sprache',
        invoiceLanguageLabel: 'Rechnungs-Sprache (Druck)',
        syncWithAppLanguage: 'Mit Anwendungs-Sprache synchronisieren',
        plan: 'Paket',
        standard: 'Standard',
        premium: 'Premium',
        bankDetails: 'Bankverbindung',
        onlinePayments: 'Online-Zahlungen',
        generalInfo: 'Allgemeine Informationen',
        taxSettings: 'Steuer-Einstellungen',
        currency: 'Währung',
        taxRate: 'Steuersatz',
        companyName: 'Firmenname',
        owner: 'Inhaber',
        street: 'Straße',
        houseNum: 'Haus-Nr.',
        zip: 'PLZ',
        city: 'Stadt',
        phone: 'Telefon',
        email: 'E-Mail',
        taxId: 'Steuernummer',
        vatId: 'USt-IdNr.',
        bankName: 'Bankname',
        iban: 'IBAN',
        paymentTerms: 'Zahlungsbedingungen',
        paymentInfo: 'Zahlungsinformationen',
        taxInfo: 'Steuerliche Angaben',

        // Invoice Form
        customerInfo: 'Kundeninformationen',
        vehicleDetails: 'Fahrzeug & Details',
        items: 'Leistungen / Ersatzteile',
        description: 'Beschreibung',
        quantity: 'Menge',
        price: 'Einzelpreis',
        addRow: 'Zeile hinzufügen',
        subtotal: 'Zwischensumme',
        tax: 'MwSt.',
        vehicle: 'Fahrzeug',
        plate: 'Kennzeichen',
        km: 'KM-Stand',

        // Statuses
        draft: 'Entwurf',
        sent: 'Gesendet',
        paid: 'Bezahlt',
        partial: 'Teilweise',
        overdue: 'Überfällig',
        invoiceDetails: 'Rechnungsdetails',
        printPdf: 'Drucken / PDF',
        payOnline: 'Online bezahlen',
        payWithPaypal: 'Mit PayPal bezahlen',
        payWithStripe: 'Mit Kreditkarte bezahlen',
        invoiceNotFound: 'Rechnung nicht gefunden',
        backToArchive: 'Zurück zum Archiv',
        saveSuccessful: 'Erfolgreich gespeichert!',
        recurringInvoices: 'Wiederkehrende Rechnungen',
        recurringInvoicesDesc: 'Vorlagen für regelmäßige Rechnungsstellung.',
        createTemplate: 'Vorlage erstellen',
        frequency: 'Frequenz',
        weekly: 'Wöchentlich',
        monthly: 'Monatlich',
        quarterly: 'Quartalsweise',
        yearly: 'Jährlich',
        upcoming: 'demnächst',
        noRecurring: 'Keine wiederkehrenden Rechnungen eingerichtet.',
        spareParts: 'Ersatzteile',
        receipts: 'Belege',
        export: 'Exportieren',
        addExpense: 'Ausgabe hinzufügen',
        amount: 'Betrag',
        noData: 'Keine Daten vorhanden',
        category: 'Kategorie',
        rent: 'Miete / Nebenkosten',
        marketing: 'Marketing',
        software: 'Software / Abos',
        insurance: 'Versicherungen',
        others: 'Sonstiges',
        businessStats: 'Geschäftsstatistik',
        revenueTrend: 'Umsatztrend (6 Monate)',

        projectDetails: 'Projekt & Referenz',
        reference: 'Referenz-Nr.',
        extraNote: 'Zusatzinfo',
        genericService: 'Leistung / Produkt',
        inProfit: 'Im Plus',
        inLoss: 'Im Minus',
        logoDisplayMode: 'Logo & Firmenname Anzeige',
        logoOnly: 'Nur Logo',
        nameOnly: 'Nur Firmenname',
        bothLogoOnTop: 'Beides - Logo oben',

        // Quotes Module
        no_quotes_found: 'Keine Angebote vorhanden.',
        quote_deletion_title: 'Angebot löschen?',
        quote_deletion_msg: 'Sind Sie sicher, dass Sie das Angebot {number} löschen möchten?',
        confirm_delete: 'Löschen',
        confirm_cancel: 'Abbrechen',
        quote_updated: 'Angebot aktualisiert!',
        invoice_updated: 'Rechnung wurde aktualisiert!',
        default_invoice_footer: 'Vielen Dank für den Auftrag!',
        default_quote_footer: 'Gerne erwarten wir Ihre Auftragserteilung.',
        quoteNotFound: 'Angebot nicht gefunden',
        backToQuotes: 'Zurück zu Angeboten',
        editQuote: 'Angebot bearbeiten',
        editInvoice: 'Rechnung bearbeiten',
        accepted: 'Akzeptiert',
        rejected: 'Abgelehnt',

        // Dynamic Industry Labels (DE)
        vehicleLabel: 'Fahrzeug',
        plateLabel: 'Kennzeichen',
        kmLabel: 'Kilometerstand',
        vinLabel: 'Fahrgestellnummer (VIN)',
        projectNameLabel: 'Projektname',
        siteAddressLabel: 'Baustellenadresse',
        workPhaseLabel: 'Bauphase',
        eventNameLabel: 'Veranstaltung',
        eventDateLabel: 'Veranstaltungsdatum',
        guestCountLabel: 'Personenzahl',
        patientIdLabel: 'Patienten-ID',
        treatmentTypeLabel: 'Behandlungsart',
        orderNumberLabel: 'Bestellnummer',
        deliveryDateLabel: 'Lieferdatum',
        workTypeLabel: 'Art der Arbeit',
        workLocationLabel: 'Einsatzort',
        consultingHoursLabel: 'Beratungsstunden',
        courseNameLabel: 'Kursbezeichnung',
        studentNameLabel: 'Teilnehmername',
        courseDurationLabel: 'Kursdauer',
        referenceLabel: 'Referenz/Projekt-Nr.',
        serviceDateLabel: 'Leistungsdatum',
        contractRefLabel: 'Auftrags-Nr.',
        venueLabel: 'Veranstaltungsort',
        treatmentDateLabel: 'Behandlungsdatum',
        insuranceRefLabel: 'Versicherungs-Nr.',
        projectPhaseLabel: 'Projektphase',
        hoursWorkedLabel: 'Arbeitsstunden',
        ticketRefLabel: 'Ticket/Auftrags-Nr.',
        deliveryAddressLabel: 'Lieferadresse',
        trackingNumberLabel: 'Sendungsnummer',
        workDurationLabel: 'Arbeitszeit (Std.)',
        materialUsedLabel: 'Verwendetes Material',
        consultingPeriodLabel: 'Beratungszeitraum',
        courseDateLabel: 'Kurszeitraum',
        notesLabel: 'Zusätzliche Notizen',

        premiumApiSection: 'Zahlungs-Schnittstellen (API Dashboard)',
        premiumApiHint: '* Diese Daten werden im Premium-Paket verwendet, um Zahlungen über Stripe und PayPal automatisch im System zu verarbeiten.',
        premiumOnly: 'NUR PREMIUM',

        // System Overview & Dashboard
        online_sales_dashboard: 'Online-Verkaufs-Dashboard',
        total_online_revenue: 'Online-Gesamtumsatz',
        total_orders: 'Gesamtbestellungen',
        critical_stock_levels: 'Kritischer Lagerbestand',
        stock_levels_healthy: 'Lagerbestand gesund.',
        live: 'LIVE',
        left: 'übrig',
        today: 'Heute',
        no_appointments_today: 'Keine Termine für heute.',

        // Module: Stock
        stockDashboard: 'Lager & Verkauf',
        totalProducts: 'Produkte Gesamt',
        lowStock: 'Niedriger Bestand',
        inventoryValue: 'Lagerwert',
        totalSales: 'Gesamtumsatz',
        recentSales: 'Aktuelle Verkäufe',
        searchSales: 'Bestellung suchen...',
        table_id: '#ID',
        table_customer: 'Kunde',
        table_status: 'Status',
        table_products: 'Produkte & Details',
        table_amount: 'Betrag',
        table_actions: 'Aktionen',
        status_shipped: 'Versendet',
        status_delivered: 'Geliefert',
        status_returned: 'Retourniert',
        status_pending: 'Ausstehend',
        no_orders: 'Keine Bestellungen gefunden.',
        tracking_modal_title: 'Sendungsinformationen',
        tracking_company: 'Versanddienstleister',
        tracking_code: 'Sendungsnummer',
        btn_save_notify: 'Speichern & Benachrichtigen',
        dataManagement: 'Datenverwaltung',
        dataManagementDesc: 'Verwenden Sie dies, wenn der Speicher voll ist oder Probleme auftreten.',
        confirmClearSales: 'Möchten Sie den Verkaufsverlauf wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
        salesCleared: 'Verkaufsverlauf wurde gelöscht.',
        clearSalesHistory: 'Verkaufsverlauf löschen',
        factoryReset: 'Auf Werkseinstellungen zurücksetzen',

        subscription_management: 'Abonnement & Zahlungen',
        integration_hub: 'Integrationen',
        subscription_title: 'Abonnement verwalten',
        subscription_desc: 'Verwalten Sie Ihren aktuellen Plan und Rechnungen.',
        current_plan: 'Aktueller Plan',
        manage_subscription: 'Abo verwalten',
        usage_limits: 'Nutzungslimits',
        billing_history: 'Rechnungshistorie',
        security_note: 'Sichere Zahlung',
        integration_desc: 'Verwalten Sie Drittanbieter-Apps und API-Schlüssel.',
        renewal_date: 'Verlängerungsdatum',

        // Reports Module
        financial_reports: 'Finanzberichte',
        stock_reports: 'Lagerberichte',
        site_progress: 'Baustellenfortschritt',
        reports_desc: 'Alle Systemberichte an einem Ort anzeigen und herunterladen.',
        search_reports: 'Berichte suchen...',
        no_reports_found: 'Keine Berichte in dieser Kategorie gefunden.',
        date_range: 'Datumsbereich',

        // Module: Appointments
        dashboard_overview: 'Übersicht',
        dashboard_subtitle: 'Ihre heutige Terminübersicht und ausstehende Aufgaben.',
        view_calendar: 'Kalender ansehen',
        all_records: 'Alle Einträge',
        stats_today_appts: 'Heutige Termine',
        stats_pending_appts: 'Ausstehende Bestätigungen',
        stats_total_services: 'Aktive Dienste',
        todays_schedule: 'Heutiger Zeitplan',
        filter: 'Filtern',
        free_today: 'Keine Termine heute',
        free_today_desc: 'Für heute sind keine Termine geplant.',
        pending_requests: 'Ausstehende Anfragen',
        tip_title: 'Tipp',
        tip_desc: 'Senden Sie Erinnerungen 1 Stunde vor Terminen, um Ausfälle zu vermeiden.',
        go_to_settings: 'Zu den Einstellungen',

        // Module: Website
        websiteManager: 'Website Manager',
        websiteDesc: 'Verwalten Sie Ihre Online-Präsenz und verkaufen Sie Produkte.',
        view_site: 'Website ansehen',
        unpublish: 'Veröffentlichung aufheben',
        publishLive: 'Veröffentlichen',
        siteLive: 'Online',
        siteDraft: 'Entwurf',
        notVisibleYet: 'Noch nicht sichtbar',
        content_status: 'Inhaltsstatus',
        active: 'Aktiv',
        automatic: 'Automatisch',
        section_unit: 'Abschnitt',
        label_products: 'Produkte',
        label_services: 'Dienstleistungen',
        label_pages: 'Seiten',
        domain_seo_desc: 'Google-Suche und Domain-Einstellungen.',
        theme_colors_desc: 'Wählen Sie ein Design, das zu Ihrer Marke passt.',
        visitors_month: 'Besucher (Monat)',
        analytics_pending: 'Google Analytics ausstehend.',
        management_edit: 'Verwaltung & Bearbeitung',
        edit_content: 'Inhalt bearbeiten',
        edit_content_desc: 'Startseite und Texte ändern.',
        domain_seo: 'Domain & SEO',
        theme_colors: 'Design & Farben',
        live_preview: 'Live-Vorschau',
        dark_mode: 'Dunkel',
        light_mode: 'Hell',
        book_now: 'Jetzt buchen',

        // Module: Accounting
        module_accounting_name: 'Rechnung',
        module_accounting_desc: 'Rechnung & Buchhaltung',
        module_appointments_name: 'Terminplaner',
        module_appointments_desc: 'Kalender & Buchung',
        module_stock_name: 'Lager & Verkauf',
        module_stock_desc: 'E-Commerce & Inventar',
        module_website_name: 'Sofort-Website',
        module_website_desc: 'Site Builder',
        module_admin_name: 'Admin Panel',
        module_admin_desc: 'Verwaltung & Einstellungen',
        apps_title: 'Anwendungen',

        // Admin Panel Specific
        admin_panel_title: 'Admin Panel',
        system_control: 'Systemsteuerung',
        switch_to_app: 'Zur Anwendung wechseln',
        management_section: 'Verwaltung',

        // User Management
        role_admin: 'Admin',
        role_manager: 'Manager',
        role_site_lead: 'Bauleiter',
        role_accountant: 'Buchhalter',
        role_worker: 'Arbeiter',
        status_active: 'Aktiv',
        status_inactive: 'Inaktiv',
        delete_confirm_message: 'Möchten Sie {name} wirklich löschen?',
        sites_placeholder: 'z.B. Baustelle A, Baustelle B',

        // Message Center
        communication_center: 'Kommunikationszentrum',
        manage_messages_alerts: 'Nachrichten verwalten',
        compose: 'Verfassen',
        compose_new: 'Neue Nachricht',
        notifications: 'Benachrichtigungen',
        search: 'Suchen...',
        reply_to_customer: 'Antwort an den Kunden...',
        reply_to_colleague: 'Antwort an den Kollegen...',
        select_item_view: 'Element zum Anzeigen auswählen',
        no_items_found: 'Keine Elemente gefunden.',
        internal_message: 'Interne Nachricht',
        customer_message_log: 'Kundennachricht',
        recipient: 'Empfänger',
        select_recipient: 'Empfänger wählen',
        all_employees: 'Alle Mitarbeiter',
        customer_placeholder: 'Kundenname / E-Mail',
        priority: 'Priorität',
        high_priority: 'Hohe Priorität',
        subject: 'Betreff',
        enter_subject: 'Betreff eingeben',
        enter_message: 'Nachricht eingeben',
        send: 'Senden',
        msg_customer: 'Kunde',

        // System Overview
        system_overview: 'Systemübersicht',
        real_time_monitoring: 'Echtzeit-Überwachung aller Module.',
        total_revenue: 'Gesamtumsatz',
        accounting_pos_sales: 'Buchhaltung + POS',
        net_profit: 'Nettogewinn',
        revenue_expenses: 'Einnahmen - Ausgaben',
        active_staff: 'Personal',
        users_with_access: 'Benutzer mit Zugriff',
        system_health: 'Systemstatus',
        all_modules_operational: 'Alle Module OK',
        week: 'Woche',
        month: 'Monat',
        year: 'Jahr',
        module_connections: 'Verbindungen',
        items_low_stock: 'Geringer Lagerbestand',
        live_website: 'Live-Website',

        // Submenus
        menu_panel_summary: 'Übersicht',
        menu_calendar: 'Kalender',
        menu_bookings: 'Termine',
        menu_services: 'Dienstleistungen',
        menu_settings: 'Einstellungen',
        menu_sales_summary: 'Verkaufsübersicht',
        menu_products_stock: 'Produkte & Lager',
        menu_pos: 'Schnellverkauf',
        menu_site_status: 'Site-Status',
        menu_site_editor: 'Editor',
        menu_domain_settings: 'Domain',
        menu_users: 'Benutzer',
        menu_messages: 'Nachrichten',

        // Invoice Paper
        page: 'Seite',
        invoiceTitle: 'RECHNUNG',
        quoteTitle: 'ANGEBOT',
        recipientLabel: 'Rechnungsempfänger:',
        detailsLabel: 'Rechnungsdetails:',
        invoiceNumberLabel: 'Rechnungsnummer:',
        invoiceDateLabel: 'Rechnungsdatum:',
        descriptionLabel: 'Beschreibung',
        quantityLabel: 'Menge',
        priceLabel: 'Einzelpreis',
        totalPriceLabel: 'Gesamtpreis',
        subtotalLabel: 'Zwischensumme (Netto):',
        taxLabel: 'Umsatzsteuer (MwSt):',
        grossTotalLabel: 'Gesamtbetrag (Brutto):',
        paymentTermsAndBank: 'Zahlungsbedingungen & Bankverbindung',
        bankLabel: 'Bank:',
        ibanLabel: 'IBAN:',
        bicLabel: 'BIC:',
        usageLabel: 'Verwendungszweck:',
        signatureLabel: 'Unterschrift',

        // Auth
        login: 'Anmelden',
        register: 'Registrieren',
        logout: 'Abmelden',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        fullName: 'Vollständiger Name',
        profileSettings: 'Profil bearbeiten',
        backToSettings: 'Zurück',
        personalInfo: 'Persönliche Infos',
        security: 'Sicherheit',
        currentPassword: 'Passwort',
        newPassword: 'Neues Passwort',
        saveChanges: 'Speichern',
        saved: 'Gespeichert!',
        manageLogo: 'Logo verwalten',
        changeLogo: 'Logo ändern',
        deleteLogo: 'Logo löschen',
        manageSignature: 'Signatur verwalten',
        signUp: 'Registrieren',
        signIn: 'Anmelden',
        rememberMe: 'Angemeldet bleiben',
        forgotPassword: 'Passwort vergessen?',
        termsAgree: 'Bedingungen akzeptieren',
        loginLink: 'Anmelden',
        invalidEmailPass: 'Ungültige E-Mail oder Passwort'
    },
    tr: {
        dashboard: 'Genel Bakış',
        appName: 'BayFatura',
        newInvoice: 'Yeni Fatura',
        quotes: 'Teklifler',
        archive: 'Arşiv',
        reports: 'Raporlar',
        expenses: 'Giderler',
        recurring: 'Düzenli',
        users: 'Kullanıcı Yönetimi',
        messages: 'Mesajlar',
        settings: 'Ayarlar',
        save: 'Kaydet',
        cancel: 'İptal',
        delete: 'Sil',
        edit: 'Düzenle',
        print: 'Yazdır',
        loading: 'Yükleniyor...',
        total: 'Toplam Tutar',
        status: 'Durum',
        date: 'Tarih',
        customer: 'Müşteri',
        invoiceNumber: 'Fatura No',
        quoteNumber: 'Teklif No',
        saveAndPrint: 'Kaydet ve Yazdır',
        actions: 'İşlemler',
        back: 'Geri',
        customerInfo: 'Müşteri Bilgileri',
        vehicleDetails: 'Araç Bilgileri',
        items: 'Hizmetler / Yedek Parçalar',
        description: 'Açıklama',
        quantity: 'Miktar',
        price: 'Birim Fiyat',
        addRow: 'Satır Ekle',
        subtotal: 'Ara Toplam',
        tax: 'KDV',
        draft: 'Taslak',
        sent: 'Gönderildi',
        paid: 'Ödendi',
        partial: 'Kısmi Ödeme',
        overdue: 'Vadesi Geçmiş',
        invoiceDetails: 'Fatura Detayları',
        profileSettings: 'Profil Ayarları',
        bankDetails: 'Banka Bilgileri',
        taxId: 'Vergi No',
        vatId: 'KDV No',
        companyName: 'Firma Adı',
        owner: 'Sahibi',
        street: 'Sokak/Cadde',
        houseNum: 'Kapı No',
        zip: 'Posta Kodu',
        city: 'Şehir',
        phone: 'Telefon',
        email: 'E-posta',
        bankName: 'Banka Adı',
        iban: 'IBAN',
        paymentTerms: 'Ödeme Koşulları',

        // Automotive Labels
        vehicleLabel: 'Araç',
        plateLabel: 'Plaka',
        kmLabel: 'Kilometre',
        vinLabel: 'Şasi No (VIN)',
        
        // Invoice Paper
        page: 'Sayfa',
        invoiceTitle: 'FATURA',
        quoteTitle: 'TEKLİF',
        recipientLabel: 'Fatura Alıcısı:',
        detailsLabel: 'Fatura Detayları:',
        invoiceNumberLabel: 'Fatura Numarası:',
        invoiceDateLabel: 'Fatura Tarihi:',
        descriptionLabel: 'Açıklama',
        quantityLabel: 'Miktar',
        priceLabel: 'Birim Fiyat',
        totalPriceLabel: 'Toplam Fiyat',
        subtotalLabel: 'Ara Toplam (Net):',
        taxLabel: 'Katma Değer Vergisi (KDV):',
        grossTotalLabel: 'Genel Toplam (Brüt):',
        paymentTermsAndBank: 'Ödeme Koşulları & Banka Bilgileri',
        bankLabel: 'Banka:',
        ibanLabel: 'IBAN:',
        bicLabel: 'BIC:',
        usageLabel: 'Açıklama:',
        signatureLabel: 'İmza',

        // Auth
        welcomeBack: 'Tekrar Hoş Geldiniz',
        getStarted: 'Hesap Oluştur',
        enterDetails: 'İşinizi yönetmek için bilgilerinizi girin',
        createAccountMsg: 'Faturalandırmaya başlamak için hesap oluşturun',
        fullName: 'Ad Soyad',
        companyNameLabel: 'Firma Adı',
        emailAddress: 'E-posta Adresi',
        passwordLabel: 'Şifre',
        loginBtn: 'Giriş Yap',
        registerBtn: 'Kayıt Ol',
        processing: 'İşleniyor...',
        orContinueWith: 'veya şununla devam et',
        noAccount: 'Hesabınız yok mu?',
        haveAccount: 'Zaten hesabınız var mı?',
        signUp: 'Kayıt Ol',
        loginLink: 'Giriş Yap',
        invalidEmailPass: 'Geçersiz e-posta veya şifre'
    }
};

export const LanguageProvider = ({ children }) => {
    const [appLanguage, setAppLanguage] = useState(() => localStorage.getItem('bay_app_lang') || 'de');
    const [invoiceLanguage, setInvoiceLanguage] = useState(() => localStorage.getItem('bay_inv_lang') || 'de');

    useEffect(() => {
        localStorage.setItem('bay_app_lang', appLanguage);
    }, [appLanguage]);

    useEffect(() => {
        localStorage.setItem('bay_inv_lang', invoiceLanguage);
    }, [invoiceLanguage]);

    const t = (key) => {
        return translations[appLanguage]?.[key] || translations['de']?.[key] || key;
    };

    const tInvoice = (key) => {
        return translations[invoiceLanguage]?.[key] || translations['de']?.[key] || key;
    };

    const LANGUAGES = [
        { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
        { code: 'tr', label: 'Türkçe', flag: '🇹🇷' }
    ];

    return (
        <LanguageContext.Provider value={{
            appLanguage,
            setAppLanguage: () => {}, // No-op
            invoiceLanguage,
            setInvoiceLanguage: () => {}, // No-op
            t,
            tInvoice,
            serviceLanguages: { invoicing: 'de', appointments: 'de', stock: 'de', website: 'de' },
            setServiceLanguage: () => {}, // No-op
            LANGUAGES
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
